server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://192.168.1.75:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: native_logs
      __path__: /var/log/*
- job_name: apache
  static_configs:
  - targets:
      - localhost
    labels:
      job: weblogs
      __path__: /var/log/apache2/*
